# Generated by Django 4.2.2 on 2023-06-09 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_book_authors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='lastName',
            new_name='last_name',
        ),
    ]
